### PR TITLE
Modularserver

### PR DESCRIPTION
**Pull request by Rsantct**

### CODE REVIEW

**Comment by Rsantct** [comment]
here it is.

**Comment by Rsantct** [comment]
pending basepaths

**Comment by rripio** [comment]
Thank you Rafa.

**Comment by rripio** [comment]
I really like the idea of this modular server, but this commit has some problems, in my view.:

1. A commit should be circumscribed to a unique motive, area, or whatever. The mod in README.md should be a separated commit.

**Pull request closed without merging**
